services:
  kafka:
    image: confluentinc/cp-kafka:7.9.0
    environment:
      CLUSTER_ID: docker-kafka-cluster
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
  backend-notification:
    build: ./backend/notification
    depends_on:
      - postgres
      - mongodb
      - kafka1
      - kafka2
      - kafka3
    environment:
      ACTIVE_PROFILES: async
      KAFKA_BOOTSTRAP_SERVERS: kafka1:19092,kafka2:19093,kafka3:19094
      KAFKA_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_SASL_MECHANISM:
      KAFKA_JAAS_CONFIG:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: springchat_notification
      MONGODB_USERNAME: springchat_notification
      MONGODB_PASSWORD: ${SPRINGCHAT_NOTIFICATION_DB_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_SENDER: ${MAIL_SENDER}
      MAIL_AUTH: ${MAIL_AUTH}
      MAIL_TLS: ${MAIL_TLS}
      MAIL_SSL: ${MAIL_SSL}
      PLATFORM_URL: ${FRONTEND_APP_URL}
