export enum ErrorResponseType {
  CHANNEL_OPERATION_NOT_ENOUGH_RIGHTS = 'CHANNEL_OPERATION_NOT_ENOUGH_RIGHTS',
  CHANNEL_MEMBER_ALREADY_ADDED = 'CHANNEL_MEMBER_ALREADY_ADDED',
  UNIQUE_EMAIL = 'UNIQUE_EMAIL',
  UNIQUE_NICKNAME = 'UNIQUE_NICKNAME',
  STOMP_DESTINATION_FORBIDDEN = 'STOMP_DESTINATION_FORBIDDEN',
  VIDEO_ROOM_ALREADY_JOINED = 'VIDEO_ROOM_ALREADY_JOINED',
  VIDEO_ROOM_PARTICIPANT_NOT_PRESENT = 'VIDEO_ROOM_PARTICIPANT_NOT_PRESENT',
  EXISTING_MEMBER = 'EXISTING_MEMBER',
}

export const getTranslationKey = (errorResponseType: ErrorResponseType) => {
  return `error.responseType.${errorResponseType}`;
};
export default {
  getTranslationKey,
};
