spring:
  kafka:
    bootstrap-servers: 127.0.0.1:29092
    properties:
      security.protocol: PLAINTEXT
      sasl.mechanism:
      sasl.jaas.config:
    admin:
      bootstrap-servers: 127.0.0.1:29092
  data:
    mongodb:
      host: localhost
      port: 27017
      database: springchat
      username: springchat
      password: springchat
  mail:
    sender: platform@example.com
    host: localhost
    port: 1025

app:
  kafka:
    topic:
      notification:
        partitions: 1
        replicas: 1
  platform:
    url: http://localhost
    email: platform@example.com

logging:
  level:
    pl.bronikowski.springchat.backendnotifications: TRACE